name: Release & Deploy

on:
  push:
    branches:
      - release

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    uses: ./.github/workflows/_release.yml
    with:
      binary-name: octask
      platforms: linux
      publish-crates: false
    secrets: inherit
